
-- -----------------------------------------------------
-- order
-- -----------------------------------------------------



-- -----------------------------------------------------
-- foods
-- -----------------------------------------------------

INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Dissolved Kebab","In a large bowl, mix the minced meat with the flour, all spices, garlic, egg and the dissolved MAGGI® Chicken Bouillon cubes until a well-combined mixture forms. Divide the mixture into small equal size balls","foods/dissolvedkebab",50,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Rice with Meat","In a large skillet, cook beef and garlic over medium heat 6-8 minutes or until beef is no longer pink, breaking up beef into crumbles. Meanwhile, in a small bowl, mix brown sugar, soy sauce, oil and seasonings.","foods/ricewithmeat",60,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Rice","Rice is the seed of the grass species Oryza sativa (Asian rice) or less commonly Oryza glaberrima (African rice). As a cereal grain, it is the most widely consumed staple food for a large part of the world's human population, especially in Asia and Africa","foods/rice",40,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Sausage","A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders. Some sausages include other ingredients for flavour","foods/sausage",45,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Okra with Meat","Bring to a boil; season with additional salt. Return the beef to the pot and add the okra. Reduce the heat to low and simmer until the okra is tender","foods/okrawithmeat",30,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Potatoes with Meat","How to Make Ground Beef and Potatoes. Lean Ground Beef. The flavorful and scrumptious meat for this dish. Potatoes. Tender cubed potatoes are a slam dunk pairing with the ground beef. Red Bell Pepper. Adds a touch of color, freshness, and sweetness. Worcestershire Sauce. Dijon Mustard. Spices. Hot Sauce.","foods/potatoeswithmeat",30,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Diffrent Greens","Different greens have different nutrients, and, generally speaking, a leaf has more nutrients the darker it is in color. We've got recipe ideas for you, too, so you ","foods/diffrentgreens",30,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mombar","Find mombar stock images in HD and millions of other royalty-free stock photos, illustrations and vectors in the Shutterstock collection.","foods/mombar",40,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Grilled Chicken","Preheat grill to medium high heat. Place chicken on the grill for 7-8 minutes. Flip over and cook an additional 7-8 minutes or until no pink remains","foods/grilledchicken",30,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Kofta","Kofta is a family of meatball or meatloaf dishes found in the Indian subcontinent, South Caucasian, Middle Eastern, Balkan, and Central Asian cuisines.","foods/kofta",70,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("liver","Eat food with fiber: Fiber helps your liver work at an optimal level. Fruits, vegetables, whole grain breads, rice and cereals can take care of your body's fiber needs","foods/liver",75,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Beef Burger","Get inspired by our juicy beef burgers. Pack your mince patties with spices from around the world and stack your buns with cheese, bacon, lettuce and more","foods/beefburger",50,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chicken Burger","Looking for the best chicken burger recipe? Whether you want to make chicken burgers for a summer BBQ, a family gathering","foods/chickenburger",40,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chicken Shawarma","What is Chicken Shawarma? Traditional chicken shawarma is basically well-marinated chicken, layered on a vertical rotisserie or spit where it's slow-roasted for days--in its own juices and fat--until perfectly tender and extra flavorful","foods/chickenshawarma",55,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Meat Shawarma","How to make beef shawarma: Step-by-step. Prepare the shawarma spices and marinade. Grab one large mixing bowl and mix together the shawarma ","foods/meatshawarma",25,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Glee","Glee Wiki is a website that anyone can edit about the FOX TV show Glee, including Glee Club, cast, music, episodes, and more","foods/glee",30,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Lamb Feathers","The ad sees SBS newsreader Lee Lin Chin and other prominent Australians bringing Aussie expats home to eat lamb on Australia","foods/lambfeathers",40,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chicken Pizza","Ditch the sausage and pepperoni and use chopped, cooked chicken to on tonight's pizza. Using chicken is easy, economical","foods/chickenpizza",50,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mix Cheese Pizza","Sauce: Combine pureed tomatoes, tomato paste, minced garlic, and basil. Spread onto prepared pizza dough. Top with sliced mozzarella cheese and bake","foods/mixcheesepizza",60,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chicken Crepe","Sauce: Combine pureed tomatoes, tomato paste, minced garlic, and basil. Spread onto prepared pizza dough. Top with sliced mozzarella cheese and bake","foods/chickencrepe",20,1,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Kofta Crepe","Meat shawrma, kofta, sausage, chicken strips, crispy chicken and escalope pane. EGP 60.00. Amazing. Dynamite Crepe. Escalope pane, spicy escalope pane","foods/koftacrepe",25,1,now());


-- -----------------------------------------------------
-- Cold Drinks
-- -----------------------------------------------------

INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Orange Juice","Orange juice is a liquid extract of the orange tree fruit, produced by squeezing or reaming oranges. It comes in several different varieties, including blood orange, navel oranges, valencia orange","cold-drinks/orangejuice",30,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Apple Juice","Start by washing and then coring the apple to remove seeds. · 2. Add the apples to the pot and add enough water to just cover","cold-drinks/applejuice",35,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mango Juice","Wash mango thoroughly and chill. · If using organic mangoes, then you can use up the skin for added fiber. · Cut the mango to cubes","cold-drinks/mangojuice",20,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Kiwi Juice","Wash and clean Kiwi fruit. Cut them crosswise. In a blender, Add the scooped out kiwi pulp, and about 1/4th cup of sugar(or as desired), a pinch of salt and water. Transfer it to serving glasses by topping","cold-drinks/kiwijuice",40,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Strawberry Juice","Wash strawberries, remove stem and cut into small pieces. ... Add strawberries, sugar and juice from lime (you can change the quantity","cold-drinks/strawberryjuice",35,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Pepsi","PepsiCo Goes Beyond. PepsiCo and Beyond Meat are joining forces in a new partnership. The goal? Dreaming up a range of snacks and beverages, all made","cold-drinks/pepsi",5,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Rani","Rani Float, the latest offering from Coca-Cola's global basket, now made in India with Indian fruits for the youth, has stepped in to offer ","cold-drinks/rani",5,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mirnda","With Miranda Hart, Patricia Hodge, Tom Ellis, Sarah Hadland. Socially inept Miranda always gets into awkward situations; working in her joke shop with best","cold-drinks/mirnda",5,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Schweppes","Schweppes Tonic Water began in 1783 as the world's original soft drink. Its founder, Jacob Schweppe, was drawn to the new art of carbonating beverages","cold-drinks/schweppes",5,2,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Lemon juice","What is lemon water? ... Share on Pinterest The vitamin C in lemons is a powerful antioxidant. Lemon water is simply the juice of lemons mixed","cold-drinks/lemonjuice",15,2,now());

-- -----------------------------------------------------
-- Hot Drinks
-- -----------------------------------------------------
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Cinnamon Tea","The easiest way to make this beverage is to simply add 1 teaspoon (2.6 grams) of ground cinnamon to 1 cup (235 ml) of boiled water and stir.","hot-drinks/cinnamontea",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Tea","Tea is an aromatic beverage commonly prepared by pouring hot or boiling water over cured or fresh leaves of Camellia sinensis, an evergreen shrub native to China and East Asia. After water, it is the most widely consumed drink in the world","hot-drinks/tea",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Peppermint Tea","To make your own peppermint tea: Bring 2 cups of water to a boil. Turn off the heat and add a handful of torn peppermint leaves to the water. Cover and steep for 5 minutes. Strain the tea and drink","hot-drinks/pepperminttea",10,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Tea with Milk","Explore the best types of tea that are traditionally enhanced with either milk and sugar or both, including some popular milk tea recipes","hot-drinks/teawithmilk",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Green Tea","Green tea has been shown to improve blood flow and lower cholesterol. A 2013 review of many studies found green tea helped prevent a range","hot-drinks/greentea",25,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Black Coffee","Nkosinathi Innocent Maphumulo (born 11 March 1976), better known by his stage name Black Coffee, is a South African DJ, record producer, singer","hot-drinks/blackcoffee",30,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Coffee with Hazelnuts","The blend of flavors—coffee, hazelnut and a bit of chocolate—make this drink absolutely sensational. It is great for breakfast or brunch, but is also wonderful","hot-drinks/coffeewithhazelnuts",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("French Coffee","Un déca is simply a decaffeinated version of espresso. As you can see, there are far less coffee variations in France than in Italy. I personally find French coffee much more bitter than Italian coffee","hot-drinks/frenchcoffee",5,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Turkish Coffee","Turkish coffee is very finely ground coffee brewed by boiling. Any coffee bean may be used; arabica varieties are considered best, but robusta or a blend ","hot-drinks/turkishcoffee",10,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Plain Sahlab","Sahlab With Nuts. EGP 10.00. Plain Sahlab. EGP 8.00. Cappuccino. EGP 10.00. Mocha Latte. EGP 15.00. Hot Lemon. EGP 7.00. Latte. EGP 15.00. Nescafe Milk","hot-drinks/plainsahlab",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Sahlab with Nuts","AbuAuf Sahlab - 250 gm New. 40.00 EGP. This traditional Middle Eastern drink is a dessert by itself, it is rich, creamy and decadent. It's a cup that fills you with","hot-drinks/sahlabwithnuts",30,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Hot Chocolate","Combine the cocoa, sugar and pinch of salt in a saucepan. Blend in the boiling water. Bring this mixture to an easy boil while you stir. ","hot-drinks/hotchocolate",35,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Milk Cinnamon","Place the milk and cinnamon bark in a small saucepan and heat almost to scalding; little bubbles should just begin forming around the perimeter","hot-drinks/milkcinnamon",30,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Forget","Forget Juice. 9 likes. We know that life is limited edition so at Forget Juice, we creatively design products that express imagination","hot-drinks/forget",20,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mint","Take charge of your finances with Mint's online budget planner. Our free budget tracker helps you understand your spending for a brighter financial future","hot-drinks/mint",40,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Nescafe Milk","The Nestlé First Milk Partnership encourages and delivers environmental stewardship on every farm. In collaboration with the Game & Wildlife Conservation Trust","hot-drinks/escafemilk",50,3,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Nescafe Black","NESCAFÉ Black Roast is bursting with rich coffee flavour for the strongest start to your morning without having to add an extra spoonful. Specially selected","hot-drinks/nescafeblack",20,3,now());

-- -----------------------------------------------------
-- Sweets
-- -----------------------------------------------------
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Strawberry Ice Cream","Homemade Strawberry Ice Cream Tips & Tricks: In a large bowl, mix the strawberries with the sugar, honey, and lemon juice, and allow the mixture to sit about 15-20 minutes. The sugars and acid from the lemon juice will release the strawberry juices, making them softer","sweets/strawberryicecream",30,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chocolate Ice Cream","Get Chocolate Ice Cream Recipe from Food Network. ... Temper the cream mixture into the eggs and sugar by gradually adding small amounts,","sweets/chocolateicecream",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Vanilla Ice Cream","Ingredients · 284ml carton double cream · 300ml full fat milk · 115g golden caster sugar · 1 vanilla pod · 3 large free-range egg yolks · have lots of ice cubes at the","sweets/vanillaicecream",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mango Ice Cream","23‏/05‏/2020 — mixing mango puree to make mango ice cream. 7. Pour the mango puree. 8. Gently fold the mango puree with whipped cream","sweets/mangoicecream",30,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mix Ice Cream","Suppliers, Manufacturers, Exporters & Importers. #oceanpower #soft ice cream mix #ice cream powder. Just when you thought GODIVA couldn't get any better","sweets/mixicecream",25,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Vanilla Milkshake","Ingredients. 200g vanilla ice cream. 500ml semi-skimmed milk, or whole milk. 2 tsp vanilla extract. melted white chocolate and sprinkles,","sweets/vanillamilkshake",35,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chocolate Milkshake","12‏/09‏/2019 — Instructions. Combine milk, chocolate syrup and chocolate ice cream in a blender. Blend until smooth. Pour into cups and garnish with whipped cream and sprinkles if desired. Serve immediately","sweets/chocolatemilkshake",15,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Strawberry Milkshake","In a mixing bowl combine the sliced strawberries, sugar and vanilla extract and stir to combine well. Set aside and allow to macerate for at least 20 minutes","sweets/strawberrymilkshake",30,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Sweet Crepe","Very good sweet crepe recipe. We used our ninja bullet to blend! the ingredients. One recipe made three large crepes","sweets/sweetcrepe",35,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Basbousa","Basbousa (Coconut Yogurt Semolina Cake) ... Who's feeling festive today? Now, don't let the beauty of this popular classic Middle Eastern cake fool you","sweets/basbousa",15,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Plain Basboush","See more of Salé Sucré Pâtisserie on Facebook. Log In. Forgot account? or. Create New Account. Not Now. Recent Post by Page. Salé Sucré Pâtisserie","sweets/plainbasboush",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mixed Sweets","looking for a gluten free option or vegetarian or prefer all sour and fizzy, you will find just what you are looking for here. Lots of different sweets in each mix","sweets/mixedsweets",25,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Knafeh Dates","Knafeh Cupcakes | Dates with Lara - Lara Samawi. Rich & creamy keshta with molten mozzarella sandwiched in a sweet and crunchy knafeh pastry topped ","sweets/knafehdates",30,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Knafeh Manga","Konafa Bil Manga, Konafa with Mango, a popular Middle-Eastern dessert. This ... Mango - Kunafa Schichtdessert aus Ägypten-- Ägyptische Rezepte Kunafa Gunafa Ramadan Dessert. Ramadan","sweets/knafehmanga",10,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Knafeh with Cream","Cream Kunafa is an Arabic dessert made with shredded filo pastry, stuffed with cream, baked till golden brown, doused in aromatic syrup and","sweets/knafehwithcream",25,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Knafeh Nablusia","Authentic Knafeh Na'ameh is typically made with Arabic cheeses like Akkawi or Nabulsia. And after some digging around, I also found out that","sweets/knafehnablusia",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Rice with milk","Use cooked rice in an equal ratio to milk or cook the rice from scratch with a high ratio of milk to rice to get the right consistency. Sweeten it to taste ","sweets/ricewithmilk",15,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("pancake","A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface","sweets/pancake",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Blueberry Cheesecake","Combine crumbs, 2 tablespoons sugar and butter. Pat mixture into the bottom of a 9 inch springform pan. Mash cream cheese until soft and creamy. Pour mixture into crumb-lined pan. Cool and then remove cake from pan by loosening edges with a knife","sweets/blueberrycheesecake",25,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chocolate Cheese Cake","Chocolate Cheesecake is a rich, creamy and chocolatey cheesecake recipe on top of a crunchy Oreo crust! This easy heesecake is for true","sweets/chocolatecheesecake",40,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Lotus Cheesecake","A creamy cheesecake with an airy, mousse-like texture that screams Lotus in every bite! Crushed Lotus biscuits in the crust, creamy Lotus in the filling, melted spread on top and a halo of Lotus crumbs to finish it off. It's a quadruple Lotus Biscoff delight that's so easy to make and doesn't require an oven","sweets/lotuscheesecake",35,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Strawberry Cheesecake","Ingredients · 250g digestive biscuits · 100g butter, melted · 1 vanilla pod · 600g full fat soft cheese · 100g icing sugar · 284ml pot of double cream","sweets/strawberrycheesecake",20,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Vanilla Cup Cake","Ingredients. 1 1/4 cups all-purpose flour. 1 1/4 tsp baking powder. 1/2 cup unsalted butter softened. 3/4 cup sugar. 2 large eggs room temperature. 2 tsp pure vanilla extract. 1/2 cup buttermilk or plain kefir, room temperature","sweets/vanillacupcake",15,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Chocolate Cupcake","This chocolate cupcake recipe makes perfect moist, fudgey, fluffy chocolate cupcakes topped with silky chocolate Swiss meringue buttercream","sweets/chocolatecupcake",10,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Ketchup","Ketchup is a table condiment or sauce. The unmodified term ketchup now typically refers to tomato ketchup, although original recipes used egg whites","sweets/ketchup",10,4,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mayonnaise","Mayonnaise is an emulsion of oil, egg yolk, and an acid, either vinegar or lemon juice; there are many variants using additional flavorings. The color varies from","sweets/mayonnaise",15,4,now());



-- -----------------------------------------------------
-- Other Foods
-- -----------------------------------------------------


INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Tahina","Tahini /təˈhiːni, tɑː-/ or tahina /-nə/ is a Middle Eastern condiment made from toasted ground hulled sesame. It is served by itself (as a dip) or as a major","other-foods/tahina",20,5,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Potatos","The potato is a root vegetable native to the Americas, a starchy tuber of the plant Solanum tuberosum, and the plant itself is a perennial in the nightshade family","other-foods/potatos",40,5,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Pickled","Pickling is the process of preserving or extending the shelf life of food by either anaerobic fermentation in brine or immersion in vinegar. The pickling procedure typically affects the food's texture, taste and flavor. The resulting food is called a pickle, or, to prevent ambiguity, prefaced with pickled","other-foods/pickled",40,5,now());
INSERT INTO orders (name,description,image,price,id_category,data_create) VALUES ("Mineral Water","Mineral water is water from a mineral spring that contains various minerals, such as salts and sulfur compounds. Mineral water may usually be still or sparkling (carbonated/effervescent) according to the presence or absence of added gases","other-foods/mineralwater",40,5,now());


